### ISSUE TITLE
The games stops after the 2nd block touches ground.

### ISSUE THREAD

**Issue by jkalandarov** [kubowania/Tetris-Basic#4]
Hi Ania,

When the 2nd block touches the ground the bottom line of the block moves down below the ground (but not shown) and the game stops (next block won't fall down). 
Also, when the 1st block touches the ground the score increases by 10.

**Comment by jkalandarov** [comment]
By the way, mini-grid is not showing the next block.

**Comment by jkalandarov** [comment]
Never mind! I found a bug and fixed it in my code!

**Comment by kubowania** [comment]
No worries :)
