### ISSUE TITLE
Learn the Fundamentals of JavaScript by building Tetris (Udemy course)

### ISSUE THREAD

**Issue by dsin125** [kubowania/Tetris-Basic#9]
Hello,

I am taking your course on Udemy to Learn JavaScript by building the tetris application. I am working off of a Mac and was able to access the terminal easily. The issue I am having is when I use the "touch", "ls" commands. I am receiving the below message.

![Screenshot](https://user-images.githubusercontent.com/65570769/87845048-106ee800-c889-11ea-9e3d-db7146377516.PNG)

**Comment by silumate** [comment]
Hi @dsin125 , this is the wrong place to ask for help.  Issues in GitHub are for describing bugs in the code, not asking for help.  I would suggest you post your question on the Udemy forum.
